# This rule is not used by the project vector-syslog-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over vectorsyslog.lab.camber.moe.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vector-syslog-operator
    app.kubernetes.io/managed-by: kustomize
  name: vectorsocketsource-admin-role
rules:
- apiGroups:
  - vectorsyslog.lab.camber.moe
  resources:
  - vectorsocketsources
  verbs:
  - '*'
- apiGroups:
  - vectorsyslog.lab.camber.moe
  resources:
  - vectorsocketsources/status
  verbs:
  - get
