## Append samples of your project ##
resources:
- vectorsyslog_v1alpha1_vectorsocketsource.yaml
- vectorsyslog_v1alpha1_vectorsyslogconfiguration.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
