apiVersion: vectorsyslog.lab.camber.moe/v1alpha1
kind: VectorSyslogConfiguration
metadata:
  name: default
  namespace: default
spec:
  globalPipeline:
    sinks:
      console_output:
        type: console
        inputs: $$VectorForSyslogOperatorSources$$
        encoding:
          codec: json
  service:
    type: LoadBalancer
  sourceSelector:
    matchLabels:
      app: myapp
  replicas: 1
  image: timberio/vector:latest-debian
